<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLVCaVdE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLVCaVdE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLVCaVdE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLVCaVdE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLVCaVdE\App_KernelDevDebugContainer([
    'container.build_hash' => 'LVCaVdE',
    'container.build_id' => 'f231d82f',
    'container.build_time' => 1591290046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLVCaVdE');
