<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYez54s8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYez54s8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYez54s8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYez54s8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYez54s8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yez54s8',
    'container.build_id' => '4c3958fe',
    'container.build_time' => 1587462505,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYez54s8');
