<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMTnimKN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMTnimKN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMTnimKN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMTnimKN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMTnimKN\App_KernelDevDebugContainer([
    'container.build_hash' => 'MTnimKN',
    'container.build_id' => '0b4ede85',
    'container.build_time' => 1587193507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMTnimKN');
